feat: KPI-281 get tags by company template
kpinetwork/frontend-prototype pull request #148
Opened 2022-10-19 21:40 UTC by FreddyJR1995

## Jira Link

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-281)

## Types of changes

- [ ] Hotfix (Bug detected)
- [x] Feature (Issue from an Active Sprint)

## Checklist:

- [x] Unit Test.
- [x] Coverage.

## Solution

2022-10-20 21:15 UTC, dsgarcia8 commented on tests/views/CompanyDetailsPanelView/Components/Tabs/TagsTab.test.jsx
> +  it('autoComplete component when tag section renderized is rendered successfully should be disabled', () => {
*Suggestion*
```suggestion
  it('autoComplete component when tag section is rendered successfully should be disabled', () => {
```

2022-10-21 14:00 UTC, kellycastrof requested changes

2022-10-21 14:00 UTC, kellycastrof commented on src/hooks/useCompanyTags.jsx
> +    const tagsListResponse = await getListOfTags({ limit, offset })
If you're not passing the limit and offset, why are you still using them?

2022-10-21 15:36 UTC, dsgarcia8 submitted a review, later dismissed

2022-10-21 21:07 UTC, dsgarcia8 approved these changes

2022-10-21 21:07 UTC, dsgarcia8 commented on src/hooks/useCompanyTags.jsx
> +      const { tags } = destructuring(result)
Autocomplete is not loading, I think It needs the isLoading to set to false

```suggestion
      const { tags } = destructuring(result)
      setIsLoading(false)
```

2022-10-21 21:46 UTC, dsgarcia8 approved these changes

2022-10-21 21:50 UTC, kellycastrof approved these changes

2022-10-21 21:51 UTC, merged